### ISSUE TITLE
アメリカの大統領選についてググると死ぬバグ

### ISSUE THREAD

**Issue by otiai10** [otiai10/chant#245]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x49c212]

goroutine 188 [running]:
chant/app/chatroom/bot.GoogleHandler.Handle(0xc2080500a0, 0xc2080859a0, 0xc20802ff90, 0xc20818e840, 0x0)
        /home/otiai10/proj/go/src/chant/app/chatroom/bot/ggl.go:47 +0x772
chant/app/chatroom/bot.Handle(0xc2080859a0, 0xc20802ff90, 0xc20818e840, 0x43ffd6)
        /home/otiai10/proj/go/src/chant/app/chatroom/bot/init.go:139 +0x159
chant/app/chatroom.func·003()
        /home/otiai10/proj/go/src/chant/app/chatroom/chatroom.go:209 +0x4b
created by chant/app/chatroom.(*Room).say
        /home/otiai10/proj/go/src/chant/app/chatroom/chatroom.go:213 +0x135

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
        /home/otiai10/.go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
        /home/otiai10/.go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010310, 0x0, 0x7f459bedd7f0, 0xc2080c47c8)
        /home/otiai10/.go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c208, 0xc208177ae8, 0x0, 0x0)
        /home/otiai10/.go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c208, 0x0, 0x0, 0x0, 0x0)
        /home/otiai10/.go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080422a0, 0x7f459bee0f58, 0xc20802c208, 0x0, 0x0)
        /home/otiai10/.go/src/net/http/server.go:1728 +0x92
github.com/revel/revel.Run(0x36b0)
        /home/otiai10/proj/go/src/github.com/revel/revel/server.go:129 +0xb01
main.main()
        /home/otiai10/proj/go/src/chant/app/tmp/main.go:184 +0x28e3
```

**Comment by otiai10** [comment]
https://github.com/otiai10/chant/blob/master/app/lib/google/client.go#L130-L131

`// とりあえず` と書いてある
